def steps(d, i, j):
        ''' generator of numbers of steps of length i and j (i < j) '''
            ''' that are needed to cover the dostance d'''
                q1, r1 = divmod(d, j)
                    if r1 != 0:
                                q1 += 1
                                        r1 = j - r1
                                            while q1 >= 0:
                                                        q2, r2 = divmod(r1, i)
                                                                if r2 == 0:
                                                                                yield q1, q2
                                                                                        if q1*j > d:
                                                                                                        r1 = j - r1
                                                                                                                else:
                                                                                                                                r1 += j
                                                                                                                                        q1 -= 1

                                                                                                                                        def knight(m, i, j):
                                                                                                                                                ''' returns min number of moves '''
                                                                                                                                                    #print('==========')
                                                                                                                                                        #print('i: {}, j: {}'.format(i,j))
                                                                                                                                                            q = 1000000
                                                                                                                                                                g1 = steps(m, i, j)
                                                                                                                                                                    while(1):
                                                                                                                                                                                try:
                                                                                                                                                                                                q1, q2 = next(g1)
                                                                                                                                                                                                            #print('q1, q2: ',q1,q2)
                                                                                                                                                                                                                        g2 = steps(m, i, j)
                                                                                                                                                                                                                                    while(1):
                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                q3, q4 = next(g2)
                                                                                                                                                                                                                                                                                                    #print('q3, q4: ',q3, q4)
                                                                                                                                                                                                                                                                                                                        if not (q1 - q4)%2 and not (q2 - q3)%2:
                                                                                                                                                                                                                                                                                                                                                    if i == j:
                                                                                                                                                                                                                                                                                                                                                                                    result = q1
                                                                                                                                                                                                                                                                                                                                                                                                                return(str(result))
                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    result = max(q1, q4) + max(q2, q3)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if result < q:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    q = result
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            #print('result: ',result)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #return str(result)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except StopIteration:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except StopIteration:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if q == 1000000:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return str(-1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return str(q)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            n = int(input())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for i in range(1, n):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            row = []
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for j in range(1, n):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    row.append(knight(n-1, *sorted([i, j])))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(' '.join(row))
